# Generated by Django 4.2 on 2023-04-10 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FileTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header_1', models.CharField(max_length=255)),
                ('header_2', models.CharField(max_length=255)),
                ('header_3', models.CharField(max_length=255)),
                ('header_4', models.CharField(max_length=255)),
                ('header_5', models.CharField(max_length=255)),
                ('header_6', models.CharField(max_length=255)),
                ('header_7', models.CharField(max_length=255)),
                ('header_8', models.CharField(max_length=255)),
                ('header_9', models.CharField(max_length=255)),
                ('header_10', models.CharField(max_length=255)),
                ('header_11', models.CharField(max_length=255)),
                ('header_12', models.CharField(max_length=255)),
                ('header_13', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'file_templates',
                'managed': True,
            },
        ),
    ]
